### ISSUE TITLE
Completar y verificar los horarios de los urbanos de Estelí

### ISSUE THREAD

**Issue by AltNico** [mapanica/pt-data-esteli#1]
En https://github.com/mapanica/coordinacion/issues/3 tenemos un papel con algo parecido a un horario de los urbanos de Estelí: [Horario Estelí Urbanos.pdf](https://github.com/mapanica/coordinacion/files/1354095/Horario.Esteli.Urbanos.pdf)

Deberíamos poner las informaciones de ese documento al [`timetable.json`](https://github.com/mapanica/pt-data-esteli/blob/master/timetable.json).

**Comment by ialokim** [comment]
Preguntando a los mismos chauferes de los buses, elaboramos un horario más exacto para las rutas 1 y 2 (falta verificar unos datos de los domingos) y por propia experiencia de la ruta 3. Ver [este PDF](https://github.com/mapanica/pt-data-esteli/files/1492709/Ruta.1.y.2.pdf).

Hasta la fecha de hoy tenemos entonces el horario de Esteli confirmado para las rutas 1 a 3, ya convertido en el formato requerido con [easy-timetable-generator](https://github.com/mapanica/easy-timetable-generator).

- [X] Ruta 1: Rosario - Hospital
- [X] Ruta 2: O. Gámez - Hospital
- [X] Ruta 3: Sandino - Hospital
- [x] Ruta 4: Villa Cuba - Hospital
- [x] Ruta 5: UNI - Roba Casa

**Comment by ialokim** [comment]
Casi todo el horario está ahora disponible y correcto, sólamente falta verificar:
- [x] #2: O. Gámez - Hospital: horario del domingo
- [ ] #4: Villa Cuba - Hospital: horario de los fines de semana
- [ ] #5: UNI - Roba Casa: horario del sábado

**Comment by ialokim** [comment]
Después de otra verificación el día de ayer, quedamos con los siguientes resultados:

- En general, los buses no cumplen muy bien los horarios los fines de semana.
- Durante dos horas en el Hospital (terminal), no pasó ningún bus del numéro 4 (Villa Cuba), así que decidimos no incluirlos en los datos, aunque debería de pasar una vez por hora.
- Parece que cada domingo cambian los turnos de los urbanos, así que los chauferes no nos podían brindar informaciones muy coherentes.

**Cabe señalar que el horario de las rutas 1 y 2 de los domingos no es muy confiable.**
No creo que aya una forma de advertir de esto en el GTFS.
